[env:rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

build_flags = -DUSE_TINYUSB

lib_deps =
    adafruit/Adafruit TinyUSB Library
    fortyseveneffects/MIDI Library

upload_protocol = picotool
